name: Comment on the pull request

on:
  workflow_run:
    workflows: ["free-programming-books-lint"]
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: pr
      - name: 'Comment on PR'
        run: |
          cat error.log
          if [ -s error.log ]
          then
            gh pr review $(<PRurl) -r -b "Linter failed, fix the error(s):
            \`\`\`
            $(cat error.log)
            \`\`\`"
            gh pr edit $(<PRurl) --add-label "linter error"
          else
            gh pr review $(<PRurl) -a
            gh pr edit $(<PRurl) --remove-label "linter error"
          fi