name: free-programming-books-lint

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_RUN_ID: ${{ github.run_id }}
  PR: ${{ github.event.pull_request.html_url }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install -g free-programming-books-lint
      
    - name: Push
      if: ${{ github.event_name == 'push' }}
      run: |
        fpb-lint ./books/
        fpb-lint ./casts/
        fpb-lint ./courses/
        fpb-lint ./more/

    - name: Pull Request
      if: ${{ always() && 
          github.event_name == 'pull_request' }}
      run: |
        fpb-lint ./books/ &>> output.log || echo "Analyzing..."
        fpb-lint ./casts/ &>> output.log || echo "Analyzing..."
        fpb-lint ./courses/ &>> output.log || echo "Analyzing..."
        fpb-lint ./more/ &>> output.log || echo "Analyzing..."

        python ./.github/workflows/clean-output.py
        cat error.log

        if [ -s error.log ]
        then
          gh pr review $PR -r -b "Linter failed, fix the error(s):
          \`\`\`
          $(cat error.log)
          \`\`\`"
          gh pr edit $PR --add-label "linter error"
        else
          gh pr review $PR -a
          gh pr edit $PR --remove-label "linter error"
        fi
