name: free-programming-books-lint

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_RUN_ID: ${{ github.run_id }}
  PR: ${{ github.event.pull_request.html_url }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install -g free-programming-books-lint
    - run: |
        fpb-lint ./books/ 2>> error-log.txt | cat error-log.txt
    - run: |
        fpb-lint ./casts/ 2>> error-log.txt | cat error-log.txt
    - run: |
        fpb-lint ./courses/ 2>> error-log.txt | cat error-log.txt
    - run: | 
        fpb-lint ./more/ 2>> error-log.txt | cat error-log.txt
    
    - name: Approve job
      if: ${{ success() &&
        github.event_name == 'pull_request' }}
      run: |
        gh pr review $PR -a
      
    - name: Error job
      if: ${{ always() &&
        failure() &&
          github.event_name == 'pull_request' }}
      run: |
        gh pr review $PR -r -b "Linter failed, fix the errors:
        \`\`\`
        $(cat error-log.txt)
        \`\`\`"
