name: free-programming-books-lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install -g free-programming-books-lint
    - run: fpb-lint ./books/
    - run: fpb-lint ./casts/
    - run: fpb-lint ./courses/
    - run: fpb-lint ./more/
    - run:
      - if ${{ success() }}
        run: |
          gh pr review -a
      - if ${{ failure() }}
        run: |
          gh pr review -r -b "Linter failed, fix the errors:
          \`\`\`
          gh run view --log-failed
          \`\`\`" 
      - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.html_url }}
